// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/get-profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/data.ts
var profile = {
  name: "Harsha Vardhan Katuri",
  role: "Firmware Engineer",
  location: "Bengaluru, India",
  headline: "Developing reliable Embedded Linux firmware, application middleware, and communication software for connected products.",
  about: "I'm a Firmware Engineer with 1.5+ years of experience developing Embedded Linux firmware and application middleware for connected products. My work focuses on C programming, protocol integration, firmware optimization, and debugging hardware-software interactions. I enjoy building reliable embedded software and continuously improving my expertise through hands-on projects involving BLE, Modbus RTU, packet parsing, board bring-up, and modern development practices including Git, GitHub Actions, CI/CD, Makefile, and Doxygen."
};
var contact = {
  email: "katuriharshavardhan369@gmail.com",
  github: "https://github.com/Harsha-vardhan-katuri",
  linkedin: "https://www.linkedin.com/in/harsha-vardhan-katuri-772166256/",
  resume: "https://drive.google.com/file/d/1lYhdQYLYqZ0BPuCR4JWuDhhuBEUk1Y5X/view?usp=drive_link"
};
var projects = [
  {
    num: "01",
    title: "Multi-Parameter Medical Device Firmware",
    tag: "Embedded C \xB7 RTOS",
    description: "Modular embedded firmware in C for SPO2, Lipid, WBC, and HbA1c on a multi-threaded POSIX pthread system. Debugged thread interactions and hardware signals using logic analyzer and oscilloscope.",
    technologies: ["Embedded C", "pthreads", "UART", "USB", "Ethernet"],
    github: "https://github.com/Harsha-vardhan-katuri/HC_FW_Code"
  },
  {
    num: "02",
    title: "Modular BLE Advertisement Analysis Framework",
    tag: "Embedded C \xB7 BLE",
    description: "Modular BLE advertisement analysis framework in Embedded C supporting four packet categories and extracting three-axis accelerometer data for motion classification, with packet validation, logging, fault handling, and fully automated CI via GitHub Actions, Makefile, and Doxygen.",
    technologies: ["Embedded C", "BLE", "GitHub Actions", "Makefile", "Doxygen"]
  },
  {
    num: "03",
    title: "GSR-Based Stress Monitoring System",
    tag: "ESP32 \xB7 Bio-Signals",
    description: "Real-time GSR pipeline on ESP32 with ADC sampling at 10-20 Hz, extracting tonic (SCL) and phasic (SCR) components to classify Calm, Normal, and Stress states with sub-second latency.",
    technologies: ["ESP32", "Grove GSR", "ADC", "DSP"],
    github: "https://github.com/Harsha-vardhan-katuri/GSR-Sensor-Project"
  },
  {
    num: "04",
    title: "LoRa Soil Health Monitoring",
    tag: "IoT \xB7 LoRa \xB7 RS485",
    description: "ESP32 reading NPK, pH, EC, moisture, and temperature via RS485 Modbus RTU, paired with SPI-based LoRa achieving 1 km range and compact 50-byte payloads for remote monitoring.",
    technologies: ["ESP32", "RS485", "LoRa", "Modbus RTU"],
    github: "https://github.com/Harsha-vardhan-katuri/Soil-Sensor-Project"
  },
  {
    num: "05",
    title: "AI Health Chatbot",
    tag: "AI \xB7 NLP \xB7 Streamlit",
    description: "Health assistant chatbot using Streamlit and Hugging Face Transformers with rule-based intent matching plus DistilGPT-2 fallback, reaching 85% response relevance and sub-2s latency.",
    technologies: ["Python", "Streamlit", "DistilGPT-2", "NLTK"],
    github: "https://github.com/Harsha-vardhan-katuri/AI_Chat_Bot",
    demo: "https://aichatbot-scmfkmwqvmvzdj9ayyzp8c.streamlit.app/"
  },
  {
    num: "06",
    title: "Packet-Based Image Projector Firmware",
    tag: "Embedded C \xB7 CI/CD",
    description: "Modular image projector software in Embedded C processing packetized image data and reconstructing display content, with packet validation, unit testing, API documentation, and CI/CD build automation.",
    technologies: ["Embedded C", "Packet Parsing", "CI/CD", "GitHub Actions", "Makefile"],
    github: "https://github.com/Harsha-vardhan-katuri/Image_Projector_Firmware"
  },
  {
    num: "07",
    title: "Bare Metal GPIO Controller",
    tag: "Bare-Metal \xB7 GPIO",
    description: "Register-level embedded firmware (DDRB, PORTB, PINB) controlling LED patterns from a debounced push-button input with finite-state logic to minimize false triggers.",
    technologies: ["Embedded C", "GPIO", "Debouncing", "AVR"],
    github: "https://github.com/Harsha-vardhan-katuri/Button_Controlled_LEDs",
    demo: "https://wokwi.com/projects/419441645494336513"
  },
  {
    num: "08",
    title: "Voice-Based Home Automation",
    tag: "IBM Cloud \xB7 IoT",
    description: "Voice-controlled home automation using IBM Watson Assistant with Speech-to-Text and Text-to-Speech, orchestrated via Node-RED flows for hands-free appliance control.",
    technologies: ["IBM Watson", "Node-RED", "STT/TTS", "Python"]
  },
  {
    num: "09",
    title: "OTP-Based Smart Wireless Lock",
    tag: "Arduino \xB7 Bluetooth",
    description: "Smart locking system on Arduino UNO with HC-05 Bluetooth and an MIT App Inventor Android app generating and validating OTPs to actuate a servo-driven lock mechanism.",
    technologies: ["Arduino", "HC-05", "Servo", "Embedded C"]
  }
];
var skills = [
  {
    category: "Programming Languages",
    items: ["C / Embedded C", "C++", "Python", "Basic Assembly"]
  },
  {
    category: "Embedded Firmware & Platform",
    items: [
      "Embedded Linux",
      "Register Level Programming",
      "State Machines / U-Boot",
      "HAL / Build Automation"
    ]
  },
  {
    category: "Communication Protocols",
    items: ["UART / SPI / I2C", "RS485 / Modbus RTU", "BLE / LoRa", "Ethernet / USB"]
  },
  {
    category: "Hardware Validation & Interfacing",
    items: [
      "GPIO / Sensor Interfacing",
      "Interrupts / Board Bring-up",
      "Packet Parsing / Protocol Analysis",
      "Logic Analyzer / Oscilloscope"
    ]
  },
  {
    category: "System on Chips & Platforms",
    items: ["ESP32", "ESP8266", "LPC2148", "TI AM335x"]
  },
  {
    category: "Tools & Environment",
    items: [
      "Git / GitHub",
      "CI/CD / GitHub Actions",
      "VS Code / Eclipse",
      "Makefile / Doxygen",
      "Ubuntu / Unit Testing"
    ]
  }
];
var experience = [
  {
    title: "Firmware Engineer",
    company: "HealthCubed India Pvt. Ltd.",
    location: "Bengaluru",
    period: "Feb 2025 \u2014 Present",
    description: "Worked on Embedded Linux firmware for a multi-parameter medical diagnostic platform, delivering feature enhancements, optimizing device communication, and improving system performance. Additionally, developed an Android application for portable, real-time soil parameter monitoring through binary packet decoding."
  },
  {
    title: "AI Internship",
    company: "Edunet Foundation (Microsoft & SAP)",
    location: "Remote",
    period: "Dec 2024 \u2014 Jan 2025",
    description: "Created an AI-powered health assistant that leverages Natural Language Processing and transformer models to understand user queries and generate meaningful responses. Optimized for response quality, low latency, and an intuitive web-based user experience."
  },
  {
    title: "Embedded Systems Trainee",
    company: "Vector India",
    location: "Hyderabad",
    period: "Jul 2023 \u2014 Apr 2024",
    description: "Completed 6+ hands-on projects in C, C++, and Embedded C, mastering microcontroller architectures, hardware interfacing, Linux internals, and device drivers using ESP8266, LPC2148, Keil IDE, and Ubuntu."
  }
];
var education = [
  {
    title: "B.Tech in Electronics & Communication Engineering",
    institution: "Gudlavalleru Engineering College",
    location: "Andhra Pradesh, India",
    period: "Aug 2019 \u2014 May 2023",
    score: "CGPA 8.36 / 10"
  },
  {
    title: "Intermediate (MPC)",
    institution: "Narayana Junior College",
    location: "Andhra Pradesh, India",
    period: "2017 \u2014 2019",
    score: "CGPA 9.94 / 10"
  },
  {
    title: "10th Grade (SSC)",
    institution: "",
    location: "Andhra Pradesh, India",
    period: "2016 \u2014 2017",
    score: "CGPA 9.0 / 10"
  }
];
var certifications = [
  {
    title: "Embedded Systems & Firmware Engineering",
    issuer: "Vector India",
    year: "2024",
    skills: ["C/C++", "Embedded C", "Microcontrollers"]
  },
  {
    title: "AI Internship \u2014 Microsoft & SAP",
    issuer: "Edunet Foundation",
    year: "2025",
    skills: ["Python", "Hugging Face", "DistilGPT-2"]
  },
  {
    title: "IoT & Cloud Communication",
    issuer: "Self-Certified Project Portfolio",
    year: "2024",
    skills: ["LoRa", "MQTT", "ThingSpeak"]
  },
  {
    title: "Linux Internals & Device Drivers",
    issuer: "Vector India",
    year: "2023",
    skills: ["Linux", "Kernel", "Drivers"]
  }
];

// src/lib/mcp/tools/get-profile.ts
var get_profile_default = defineTool({
  name: "get_profile",
  title: "Get profile",
  description: "Get Harsha Vardhan Katuri's professional profile summary: name, role, location, headline, about text, and public contact links.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const payload = { ...profile, contact };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-projects.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";
var list_projects_default = defineTool2({
  name: "list_projects",
  title: "List projects",
  description: "List the portfolio's engineering projects with titles, descriptions, technologies, and GitHub/demo links. Optionally filter by a free-text query matched against title, description, and technologies.",
  inputSchema: {
    query: z.string().optional().describe("Optional case-insensitive keyword filter, e.g. 'BLE' or 'ESP32'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ query }) => {
    const q = query?.trim().toLowerCase();
    const results = q ? projects.filter(
      (p) => [p.title, p.description, p.tag, ...p.technologies].join(" ").toLowerCase().includes(q)
    ) : projects;
    return {
      content: [{ type: "text", text: JSON.stringify(results, null, 2) }],
      structuredContent: { count: results.length, projects: results }
    };
  }
});

// src/lib/mcp/tools/get-skills.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
var get_skills_default = defineTool3({
  name: "get_skills",
  title: "Get skills",
  description: "Get the technical skill set grouped by category: programming languages, embedded firmware, communication protocols, hardware validation, SoCs, and tooling.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(skills, null, 2) }],
    structuredContent: { categories: skills }
  })
});

// src/lib/mcp/tools/get-experience.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
var get_experience_default = defineTool4({
  name: "get_experience",
  title: "Get work experience",
  description: "Get the professional work and training history, including role, company, location, period, and a description of the work done.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(experience, null, 2) }],
    structuredContent: { experience }
  })
});

// src/lib/mcp/tools/get-education.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.2";
var get_education_default = defineTool5({
  name: "get_education",
  title: "Get education and certifications",
  description: "Get academic history (degree, institution, period, scores) together with professional certifications and their issuers.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const payload = { education, certifications };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "portfolio",
  title: "Portfolio",
  version: "0.1.0",
  instructions: "Tools for Harsha Vardhan Katuri's firmware engineering portfolio. Use `get_profile` for a summary and contact links, `list_projects` to browse or search projects, `get_skills` for the technical skill set, `get_experience` for work history, and `get_education` for academics and certifications. All data is public portfolio content.",
  tools: [
    get_profile_default,
    list_projects_default,
    get_skills_default,
    get_experience_default,
    get_education_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
